"""ADIF (Amateur Data Interchange Format) utilities."""

ADIF_FIELDS = [
    "qso_date", "qso_date_off", "time_on", "time_off", "callsign", "name",
    "mode", "freq", "band", "rst_sent", "rst_rcvd", "gridsquare",
    "my_gridsquare", "qth", "state", "dxcc", "cq_zone", "itu_zone",
    "tx_pwr", "my_pota_ref", "pota_ref", "comment", "notes",
]


# Maps internal field names to ADIF tag names where they differ
_ADIF_TAG_MAP = {
    "callsign":  "CALL",
    "cq_zone":   "CQZ",
    "itu_zone":  "ITUZ",
}


def _field(tag: str, value: str) -> str:
    """Return an ADIF field like <TAG:N>value."""
    adif_tag = _ADIF_TAG_MAP.get(tag, tag).upper()
    return f"<{adif_tag}:{len(value)}>{value}"


def qso_to_adif(qso: dict) -> str:
    """Convert a QSO dict to an ADIF record string."""
    parts = []
    for key in ADIF_FIELDS:
        val = qso.get(key)
        if val:
            # Normalise date: 2023-05-12 -> 20230512
            if key in ("qso_date", "qso_date_off"):
                val = val.replace("-", "")
            # Normalise time: 15:24 -> 1524
            if key in ("time_on", "time_off"):
                val = val.replace(":", "")
            parts.append(_field(key, str(val)))
    parts.append("<EOR>")
    return " ".join(parts)


def logbook_to_adif(qso_list: list) -> str:
    """Convert a list of QSO dicts to a full ADIF file string."""
    header = (
        "ADIF export generated by Ham Logbook App\n"
        "<ADIF_VER:5>3.1.4\n"
        "<PROGRAMID:14>HamLogbookApp\n"
        "<EOH>\n\n"
    )
    records = "\n".join(qso_to_adif(q) for q in qso_list)
    return header + records


def parse_adif(text: str) -> list:
    """Parse an ADIF file/string and return a list of QSO dicts."""
    import re
    # Skip header
    eoh = text.upper().find("<EOH>")
    if eoh != -1:
        text = text[eoh + 5:]

    records = []
    for record in re.split(r"<EOR>", text, flags=re.IGNORECASE):
        record = record.strip()
        if not record:
            continue
        qso = {}
        for m in re.finditer(r"<(\w+)(?::\d+(?::\w)?)?>([^<]*)", record):
            tag = m.group(1).lower()
            value = m.group(2).strip()
            if tag and value:
                # Normalise date back: 20230512 -> 2023-05-12
                if tag in ("qso_date", "qso_date_off") and len(value) == 8:
                    value = f"{value[:4]}-{value[4:6]}-{value[6:]}"
                # Normalise time back: 1524 -> 15:24
                if tag in ("time_on", "time_off") and len(value) >= 4:
                    value = f"{value[:2]}:{value[2:4]}"
                qso[tag] = value
        if qso.get("callsign") and qso.get("qso_date") and qso.get("time_on"):
            records.append(qso)
    return records
